export {
  userRelations,
  accountRelations,
  sessionRelations,
  passkeyRelations,
  loginHistoryRelations,
  categoryRelations,
  mediaRelations,
  postRelations,
  tagRelations,
  postTagRelations,
  pageRelations,
  commentRelations,
  menuRelations,
} from "./schema";
