import type { MetricLabelName } from "./names";

export const databaseQueryNames = [
  "auth.context-user",
  "auth.credentials-user",
  "auth.oauth-user.create",
  "auth.user-by-email",
  "category.create",
  "category.destroy",
  "category.list",
  "category.service.count",
  "category.service.list",
  "category.update",
  "comment.create",
  "comment.notification.detail",
  "comment.notification.setting",
  "comment.service.count",
  "comment.service.create",
  "comment.service.custom-posts",
  "comment.service.destroy",
  "comment.service.ids",
  "comment.service.list",
  "comment.service.public-count",
  "comment.service.public-list",
  "comment.service.update",
  "comment.target.page",
  "comment.target.parent",
  "comment.target.post",
  "link.create",
  "link.destroy",
  "link.service.count",
  "link.service.list",
  "link.update",
  "media.count",
  "media.create",
  "media.destroy.delete",
  "media.destroy.select",
  "media.list",
  "menu.save-all",
  "menu.service.categories",
  "menu.service.list",
  "menu.service.pages",
  "page.create",
  "page.destroy",
  "page.increment-views",
  "page.service.author",
  "page.service.count",
  "page.service.detail",
  "page.service.detail-images",
  "page.service.images",
  "page.service.list",
  "page.service.relations",
  "page.update",
  "post.category-id",
  "post.create",
  "post.destroy",
  "post.increment-views",
  "post.random-by-category",
  "post.service.category-tree",
  "post.service.count",
  "post.service.detail",
  "post.service.detail-images",
  "post.service.ids-by-tag",
  "post.service.list",
  "post.service.relations",
  "post.update",
  "post.update-tags",
  "setting.get",
  "setting.update",
  "statistics.comments-by-status",
  "statistics.posts-by-author",
  "statistics.posts-by-type",
  "statistics.user-list",
  "statistics.users-by-level",
  "tag.count",
  "tag.create",
  "tag.destroy",
  "tag.list",
  "tag.relations",
  "tag.update",
  "user.count",
  "user.create",
  "user.current",
  "user.destroy",
  "user.detail",
  "user.list",
  "user.update",
] as const;

const procedureNames = [
  "category.adminIndex",
  "category.create",
  "category.destroy",
  "category.index",
  "category.update",
  "comment.create",
  "comment.destroy",
  "comment.index",
  "comment.listByRef",
  "comment.update",
  "link.adminIndex",
  "link.create",
  "link.destroy",
  "link.index",
  "link.update",
  "media.destroy",
  "media.getPresignedUrl",
  "media.index",
  "media.upload",
  "menu.adminIndex",
  "menu.index",
  "menu.saveAll",
  "page.adminDetail",
  "page.adminIndex",
  "page.create",
  "page.destroy",
  "page.detail",
  "page.incrementViews",
  "page.index",
  "page.update",
  "post.adminDetail",
  "post.adminIndex",
  "post.create",
  "post.destroy",
  "post.detail",
  "post.getCategoryId",
  "post.getRandomByCategory",
  "post.incrementViews",
  "post.index",
  "post.update",
  "post.updateTags",
  "setting.index",
  "setting.update",
  "statistic.index",
  "tag.create",
  "tag.destroy",
  "tag.index",
  "tag.update",
  "user.create",
  "user.current",
  "user.destroy",
  "user.detail",
  "user.index",
  "user.update",
  // 为中间件契约测试提供稳定的合成过程名称。
  "observed",
] as const;

const metricLabelValues = {
  procedure: procedureNames,
  method: ["query", "mutation", "subscription"],
  outcome: [
    "success",
    "error",
    "PARSE_ERROR",
    "BAD_REQUEST",
    "INTERNAL_SERVER_ERROR",
    "NOT_IMPLEMENTED",
    "BAD_GATEWAY",
    "SERVICE_UNAVAILABLE",
    "GATEWAY_TIMEOUT",
    "UNAUTHORIZED",
    "PAYMENT_REQUIRED",
    "FORBIDDEN",
    "NOT_FOUND",
    "METHOD_NOT_SUPPORTED",
    "TIMEOUT",
    "CONFLICT",
    "PRECONDITION_FAILED",
    "PAYLOAD_TOO_LARGE",
    "UNSUPPORTED_MEDIA_TYPE",
    "UNPROCESSABLE_CONTENT",
    "TOO_MANY_REQUESTS",
    "CLIENT_CLOSED_REQUEST",
  ],
  queryName: databaseQueryNames,
  operation: [
    "select",
    "insert",
    "update",
    "delete",
    "transaction",
    "read",
    "hit",
    "miss",
    "write",
    "error",
    "validate",
    "send",
    "put",
    "presign",
  ],
  namespace: ["post.index"],
  service: ["captcha", "email", "object-storage"],
} as const satisfies Record<MetricLabelName, readonly string[]>;

export const metricLabelValueCatalog: Readonly<
  Record<MetricLabelName, ReadonlySet<string>>
> = {
  procedure: new Set(metricLabelValues.procedure),
  method: new Set(metricLabelValues.method),
  outcome: new Set(metricLabelValues.outcome),
  queryName: new Set(metricLabelValues.queryName),
  operation: new Set(metricLabelValues.operation),
  namespace: new Set(metricLabelValues.namespace),
  service: new Set(metricLabelValues.service),
};
