export const {
  userRelations,
  accountRelations,
  sessionRelations,
  passkeyRelations,
  loginHistoryRelations,
  categoryRelations,
  categoryTranslationRelations,
  mediaRelations,
  postRelations,
  postTranslationRelations,
  tagRelations,
  tagTranslationRelations,
  postTagRelations,
  pageRelations,
  pageTranslationRelations,
  commentRelations,
  menuRelations,
  settingRelations,
  settingTranslationRelations,
} = defineRelations({
  user,
  account,
  session,
  passkey,
  loginHistory,
  category,
  categoryTranslation,
  media,
  post,
  postTranslation,
  tag,
  tagTranslation,
  postTag,
  page,
  pageTranslation,
  comment,
  menu,
  setting,
  settingTranslation,
});
import { defineRelations } from "../define-relations";
import {
  user,
  account,
  passkey,
  session,
  loginHistory,
} from "./auth";
import {
  category,
  categoryTranslation,
  media,
  post,
  postTranslation,
  tag,
  tagTranslation,
  postTag,
  page,
  pageTranslation,
  comment,
  menu,
  setting,
  settingTranslation,
} from "./content";
