import { Permission, type Permission as PermissionValue } from "@/packages/identity/auth/permissions";
import { UserLevel } from "@/packages/domain/identity/user";

const ALL_ROLES = [UserLevel.ADMIN, UserLevel.EDITOR, UserLevel.GUEST] as const;
const ADMIN_EDITOR = [UserLevel.ADMIN, UserLevel.EDITOR] as const;
const ADMIN_ONLY = [UserLevel.ADMIN] as const;

type CapabilityMatrixEntry = readonly [
  path: string,
  permission: PermissionValue,
  allowedRoles: readonly UserLevel[],
  input: unknown,
  firstBoundary: "database" | "hash" | "storage",
];

const TEST_ID = "0123456789abcdef01234567";
const LIST_INPUT = {};
const DELETE_INPUT = { ids: [TEST_ID] };
const I18N_INPUT = { en: "Test", zh: "测试" };

export const capabilityProcedureMatrix: readonly CapabilityMatrixEntry[] = [
  [
    "accountSecurity.loginHistory",
    Permission.userReadSelf,
    ALL_ROLES,
    undefined,
    "database",
  ],
  [
    "category.adminIndex",
    Permission.categoryReadAll,
    ALL_ROLES,
    LIST_INPUT,
    "database",
  ],
  [
    "category.create",
    Permission.categoryCreate,
    ADMIN_EDITOR,
    {
      title: I18N_INPUT,
      description: I18N_INPUT,
      path: "/test",
      status: "ENABLE",
    },
    "database",
  ],
  [
    "category.destroy",
    Permission.categoryDelete,
    ADMIN_EDITOR,
    DELETE_INPUT,
    "database",
  ],
  [
    "category.update",
    Permission.categoryUpdate,
    ADMIN_EDITOR,
    { id: TEST_ID },
    "database",
  ],
  [
    "comment.index",
    Permission.commentReadAll,
    ALL_ROLES,
    LIST_INPUT,
    "database",
  ],
  [
    "comment.update",
    Permission.commentModerate,
    ADMIN_ONLY,
    { id: TEST_ID },
    "database",
  ],
  [
    "comment.destroy",
    Permission.commentModerate,
    ADMIN_ONLY,
    DELETE_INPUT,
    "database",
  ],
  [
    "link.adminIndex",
    Permission.linkReadAll,
    ALL_ROLES,
    LIST_INPUT,
    "database",
  ],
  [
    "link.create",
    Permission.linkCreate,
    ADMIN_ONLY,
    {
      name: "Test",
      url: "https://example.test",
      logo: "https://example.test/logo.png",
      status: "ENABLE",
    },
    "database",
  ],
  ["link.destroy", Permission.linkDelete, ADMIN_ONLY, DELETE_INPUT, "database"],
  [
    "link.update",
    Permission.linkUpdate,
    ADMIN_ONLY,
    { id: TEST_ID },
    "database",
  ],
  ["media.index", Permission.mediaReadAll, ALL_ROLES, LIST_INPUT, "database"],
  [
    "media.getPresignedUrl",
    Permission.mediaUpload,
    ADMIN_EDITOR,
    { name: "test.jpg", type: "image/jpeg" },
    "storage",
  ],
  [
    "media.upload",
    Permission.mediaUpload,
    ADMIN_EDITOR,
    { name: "test.jpg", size: 1, type: "image/jpeg", key: "test.jpg" },
    "database",
  ],
  [
    "media.destroy",
    Permission.mediaDelete,
    ADMIN_EDITOR,
    DELETE_INPUT,
    "database",
  ],
  ["menu.adminIndex", Permission.menuReadAll, ALL_ROLES, undefined, "database"],
  ["menu.saveAll", Permission.menuUpdate, ADMIN_EDITOR, [], "database"],
  [
    "page.adminIndex",
    Permission.pageReadAll,
    ALL_ROLES,
    LIST_INPUT,
    "database",
  ],
  [
    "page.adminDetail",
    Permission.pageReadAll,
    ALL_ROLES,
    { id: TEST_ID },
    "database",
  ],
  [
    "page.create",
    Permission.pageCreate,
    ADMIN_EDITOR,
    {
      title: I18N_INPUT,
      content: I18N_INPUT,
      status: "PUBLISH",
      template: "default",
    },
    "database",
  ],
  [
    "page.destroy",
    Permission.pageDelete,
    ADMIN_EDITOR,
    DELETE_INPUT,
    "database",
  ],
  [
    "page.update",
    Permission.pageUpdate,
    ADMIN_EDITOR,
    { id: TEST_ID },
    "database",
  ],
  [
    "post.adminIndex",
    Permission.postReadAll,
    ALL_ROLES,
    LIST_INPUT,
    "database",
  ],
  [
    "post.adminDetail",
    Permission.postReadAll,
    ALL_ROLES,
    { id: TEST_ID },
    "database",
  ],
  [
    "post.create",
    Permission.postCreate,
    ADMIN_EDITOR,
    {
      title: I18N_INPUT,
      content: I18N_INPUT,
      status: "PUBLISH",
      type: "ARTICLE",
      categoryId: TEST_ID,
    },
    "database",
  ],
  [
    "post.destroy",
    Permission.postDelete,
    ADMIN_EDITOR,
    DELETE_INPUT,
    "database",
  ],
  [
    "post.update",
    Permission.postUpdate,
    ADMIN_EDITOR,
    { id: TEST_ID },
    "database",
  ],
  [
    "post.updateTags",
    Permission.postManageTags,
    ADMIN_EDITOR,
    { postId: TEST_ID, tagIds: [TEST_ID], type: "ACTOR" },
    "database",
  ],
  [
    "setting.update",
    Permission.settingUpdate,
    ADMIN_ONLY,
    {
      id: TEST_ID,
      siteName: I18N_INPUT,
      siteSubName: I18N_INPUT,
      siteSignature: I18N_INPUT,
      siteCopyright: I18N_INPUT,
    },
    "database",
  ],
  [
    "statistic.index",
    Permission.statisticsRead,
    ALL_ROLES,
    undefined,
    "database",
  ],
  [
    "tag.create",
    Permission.tagCreate,
    ADMIN_EDITOR,
    { name: I18N_INPUT },
    "database",
  ],
  ["tag.destroy", Permission.tagDelete, ADMIN_ONLY, DELETE_INPUT, "database"],
  [
    "tag.update",
    Permission.tagUpdate,
    ADMIN_EDITOR,
    { id: TEST_ID },
    "database",
  ],
  ["user.current", Permission.userReadSelf, ALL_ROLES, undefined, "database"],
  ["user.index", Permission.userReadAll, ADMIN_EDITOR, LIST_INPUT, "database"],
  [
    "user.create",
    Permission.userManage,
    ADMIN_ONLY,
    {
      name: "Test",
      email: "test@example.test",
      password: "password123",
      level: UserLevel.EDITOR,
      status: "ENABLE",
    },
    "database",
  ],
  ["user.destroy", Permission.userManage, ADMIN_ONLY, DELETE_INPUT, "database"],
  [
    "user.update",
    Permission.userManage,
    ADMIN_ONLY,
    { id: TEST_ID },
    "database",
  ],
];

